name: Build IPA

on:
  push:
    branches:
      - main  # Thay đổi branch nếu cần

jobs:
  build:
    runs-on: macos-latest  # Chạy trên macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies (nếu có)
      run: |
        #cd iOSKPAH  # Đường dẫn đến dự án Xcode
        # Nếu cần cài đặt dependencies, thêm lệnh ở đây

    - name: Build IPA
      run: |
        xcodebuild -project Unity-iPhone.xcodeproj -scheme YourScheme -archivePath ./build/Unity-iPhone.xcodeproj archive
        xcodebuild -exportArchive -archivePath ./build/Unity-iPhone.xcodeproj -exportOptionsPlist ./Info.plist -exportPath ./build

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: YourApp.ipa
        path: ./build/YourApp.ipa
